/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lewwlvzooauwjpvbnnib"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxld3dsdnpvb2F1d2pwdmJubmliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2NzcyMzksImV4cCI6MjA4NTI1MzIzOX0.Z0BvuhNKYH-jn-m-bskI3z7o_mJZ0OkI8wG2BBdq28A"